//to compile protoc --go_out=. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: rvInterface.proto

package rvInterface

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Student struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
}

func (x *Student) Reset() {
	*x = Student{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rvInterface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Student) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Student) ProtoMessage() {}

func (x *Student) ProtoReflect() protoreflect.Message {
	mi := &file_rvInterface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Student.ProtoReflect.Descriptor instead.
func (*Student) Descriptor() ([]byte, []int) {
	return file_rvInterface_proto_rawDescGZIP(), []int{0}
}

func (x *Student) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eligible bool  `protobuf:"varint,1,opt,name=Eligible,proto3" json:"Eligible,omitempty"`
	Time     int64 `protobuf:"varint,2,opt,name=Time,proto3" json:"Time,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rvInterface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_rvInterface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_rvInterface_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetEligible() bool {
	if x != nil {
		return x.Eligible
	}
	return false
}

func (x *Response) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

var File_rvInterface_proto protoreflect.FileDescriptor

var file_rvInterface_proto_rawDesc = []byte{
	0x0a, 0x11, 0x72, 0x76, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x76, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65,
	0x22, 0x1f, 0x0a, 0x07, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x22, 0x3a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x45, 0x6c, 0x69, 0x67, 0x69, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x32, 0x56, 0x0a,
	0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x61, 0x6c,
	0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x0b, 0x63, 0x68, 0x65, 0x63, 0x6b,
	0x52, 0x65, 0x67, 0x56, 0x61, 0x6c, 0x12, 0x14, 0x2e, 0x72, 0x76, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x66, 0x61, 0x63, 0x65, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x72,
	0x76, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x72, 0x76, 0x49, 0x6e, 0x74,
	0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rvInterface_proto_rawDescOnce sync.Once
	file_rvInterface_proto_rawDescData = file_rvInterface_proto_rawDesc
)

func file_rvInterface_proto_rawDescGZIP() []byte {
	file_rvInterface_proto_rawDescOnce.Do(func() {
		file_rvInterface_proto_rawDescData = protoimpl.X.CompressGZIP(file_rvInterface_proto_rawDescData)
	})
	return file_rvInterface_proto_rawDescData
}

var file_rvInterface_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rvInterface_proto_goTypes = []interface{}{
	(*Student)(nil),  // 0: rvInterface.Student
	(*Response)(nil), // 1: rvInterface.Response
}
var file_rvInterface_proto_depIdxs = []int32{
	0, // 0: rvInterface.RegistrationValidation.checkRegVal:input_type -> rvInterface.Student
	1, // 1: rvInterface.RegistrationValidation.checkRegVal:output_type -> rvInterface.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rvInterface_proto_init() }
func file_rvInterface_proto_init() {
	if File_rvInterface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rvInterface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Student); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rvInterface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rvInterface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rvInterface_proto_goTypes,
		DependencyIndexes: file_rvInterface_proto_depIdxs,
		MessageInfos:      file_rvInterface_proto_msgTypes,
	}.Build()
	File_rvInterface_proto = out.File
	file_rvInterface_proto_rawDesc = nil
	file_rvInterface_proto_goTypes = nil
	file_rvInterface_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegistrationValidationClient is the client API for RegistrationValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegistrationValidationClient interface {
	CheckRegVal(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Response, error)
}

type registrationValidationClient struct {
	cc grpc.ClientConnInterface
}

func NewRegistrationValidationClient(cc grpc.ClientConnInterface) RegistrationValidationClient {
	return &registrationValidationClient{cc}
}

func (c *registrationValidationClient) CheckRegVal(ctx context.Context, in *Student, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/rvInterface.RegistrationValidation/checkRegVal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegistrationValidationServer is the server API for RegistrationValidation service.
type RegistrationValidationServer interface {
	CheckRegVal(context.Context, *Student) (*Response, error)
}

// UnimplementedRegistrationValidationServer can be embedded to have forward compatible implementations.
type UnimplementedRegistrationValidationServer struct {
}

func (*UnimplementedRegistrationValidationServer) CheckRegVal(context.Context, *Student) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckRegVal not implemented")
}

func RegisterRegistrationValidationServer(s *grpc.Server, srv RegistrationValidationServer) {
	s.RegisterService(&_RegistrationValidation_serviceDesc, srv)
}

func _RegistrationValidation_CheckRegVal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Student)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegistrationValidationServer).CheckRegVal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rvInterface.RegistrationValidation/CheckRegVal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegistrationValidationServer).CheckRegVal(ctx, req.(*Student))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegistrationValidation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rvInterface.RegistrationValidation",
	HandlerType: (*RegistrationValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "checkRegVal",
			Handler:    _RegistrationValidation_CheckRegVal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rvInterface.proto",
}
