// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Tokens

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LoginEndpointClient is the client API for LoginEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoginEndpointClient interface {
	AddToList(ctx context.Context, in *Addition, opts ...grpc.CallOption) (*Token, error)
	DropFromList(ctx context.Context, in *Addition, opts ...grpc.CallOption) (*Token, error)
	PingList(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error)
}

type loginEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewLoginEndpointClient(cc grpc.ClientConnInterface) LoginEndpointClient {
	return &loginEndpointClient{cc}
}

func (c *loginEndpointClient) AddToList(ctx context.Context, in *Addition, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/Tokens.LoginEndpoint/addToList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginEndpointClient) DropFromList(ctx context.Context, in *Addition, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/Tokens.LoginEndpoint/dropFromList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loginEndpointClient) PingList(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Token, error) {
	out := new(Token)
	err := c.cc.Invoke(ctx, "/Tokens.LoginEndpoint/pingList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LoginEndpointServer is the server API for LoginEndpoint service.
// All implementations must embed UnimplementedLoginEndpointServer
// for forward compatibility
type LoginEndpointServer interface {
	AddToList(context.Context, *Addition) (*Token, error)
	DropFromList(context.Context, *Addition) (*Token, error)
	PingList(context.Context, *Token) (*Token, error)
	mustEmbedUnimplementedLoginEndpointServer()
}

// UnimplementedLoginEndpointServer must be embedded to have forward compatible implementations.
type UnimplementedLoginEndpointServer struct {
}

func (UnimplementedLoginEndpointServer) AddToList(context.Context, *Addition) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToList not implemented")
}
func (UnimplementedLoginEndpointServer) DropFromList(context.Context, *Addition) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropFromList not implemented")
}
func (UnimplementedLoginEndpointServer) PingList(context.Context, *Token) (*Token, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PingList not implemented")
}
func (UnimplementedLoginEndpointServer) mustEmbedUnimplementedLoginEndpointServer() {}

// UnsafeLoginEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoginEndpointServer will
// result in compilation errors.
type UnsafeLoginEndpointServer interface {
	mustEmbedUnimplementedLoginEndpointServer()
}

func RegisterLoginEndpointServer(s grpc.ServiceRegistrar, srv LoginEndpointServer) {
	s.RegisterService(&LoginEndpoint_ServiceDesc, srv)
}

func _LoginEndpoint_AddToList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Addition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginEndpointServer).AddToList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tokens.LoginEndpoint/addToList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginEndpointServer).AddToList(ctx, req.(*Addition))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginEndpoint_DropFromList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Addition)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginEndpointServer).DropFromList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tokens.LoginEndpoint/dropFromList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginEndpointServer).DropFromList(ctx, req.(*Addition))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoginEndpoint_PingList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoginEndpointServer).PingList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Tokens.LoginEndpoint/pingList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoginEndpointServer).PingList(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

// LoginEndpoint_ServiceDesc is the grpc.ServiceDesc for LoginEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoginEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Tokens.LoginEndpoint",
	HandlerType: (*LoginEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "addToList",
			Handler:    _LoginEndpoint_AddToList_Handler,
		},
		{
			MethodName: "dropFromList",
			Handler:    _LoginEndpoint_DropFromList_Handler,
		},
		{
			MethodName: "pingList",
			Handler:    _LoginEndpoint_PingList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "token.proto",
}
