// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: pb/dbRequests.proto

package dbRequests

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ReceiveClassesParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ReceiveClassesParams) Reset() {
	*x = ReceiveClassesParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_dbRequests_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveClassesParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveClassesParams) ProtoMessage() {}

func (x *ReceiveClassesParams) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dbRequests_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveClassesParams.ProtoReflect.Descriptor instead.
func (*ReceiveClassesParams) Descriptor() ([]byte, []int) {
	return file_pb_dbRequests_proto_rawDescGZIP(), []int{0}
}

type ClassesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Classes []*Class `protobuf:"bytes,1,rep,name=classes,proto3" json:"classes,omitempty"`
}

func (x *ClassesResponse) Reset() {
	*x = ClassesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_dbRequests_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassesResponse) ProtoMessage() {}

func (x *ClassesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dbRequests_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassesResponse.ProtoReflect.Descriptor instead.
func (*ClassesResponse) Descriptor() ([]byte, []int) {
	return file_pb_dbRequests_proto_rawDescGZIP(), []int{1}
}

func (x *ClassesResponse) GetClasses() []*Class {
	if x != nil {
		return x.Classes
	}
	return nil
}

type Class struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Location        string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	Level           string   `protobuf:"bytes,2,opt,name=level,proto3" json:"level,omitempty"`
	School          int32    `protobuf:"varint,3,opt,name=school,proto3" json:"school,omitempty"`
	Department      int32    `protobuf:"varint,4,opt,name=department,proto3" json:"department,omitempty"`
	ClassNum        int32    `protobuf:"varint,5,opt,name=classNum,proto3" json:"classNum,omitempty"`
	Index           string   `protobuf:"bytes,6,opt,name=index,proto3" json:"index,omitempty"`
	Name            string   `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Section         string   `protobuf:"bytes,8,opt,name=section,proto3" json:"section,omitempty"`
	MeetingLocation string   `protobuf:"bytes,9,opt,name=meeting_location,json=meetingLocation,proto3" json:"meeting_location,omitempty"`
	MeetingTimes    string   `protobuf:"bytes,10,opt,name=meeting_times,json=meetingTimes,proto3" json:"meeting_times,omitempty"`
	Exam            string   `protobuf:"bytes,11,opt,name=exam,proto3" json:"exam,omitempty"`
	Instructors     []string `protobuf:"bytes,12,rep,name=instructors,proto3" json:"instructors,omitempty"`
	Codes           []string `protobuf:"bytes,13,rep,name=codes,proto3" json:"codes,omitempty"`
	Synopsis        string   `protobuf:"bytes,14,opt,name=synopsis,proto3" json:"synopsis,omitempty"`
	Books           []string `protobuf:"bytes,15,rep,name=books,proto3" json:"books,omitempty"`
	Available       bool     `protobuf:"varint,16,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *Class) Reset() {
	*x = Class{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_dbRequests_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Class) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Class) ProtoMessage() {}

func (x *Class) ProtoReflect() protoreflect.Message {
	mi := &file_pb_dbRequests_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Class.ProtoReflect.Descriptor instead.
func (*Class) Descriptor() ([]byte, []int) {
	return file_pb_dbRequests_proto_rawDescGZIP(), []int{2}
}

func (x *Class) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Class) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *Class) GetSchool() int32 {
	if x != nil {
		return x.School
	}
	return 0
}

func (x *Class) GetDepartment() int32 {
	if x != nil {
		return x.Department
	}
	return 0
}

func (x *Class) GetClassNum() int32 {
	if x != nil {
		return x.ClassNum
	}
	return 0
}

func (x *Class) GetIndex() string {
	if x != nil {
		return x.Index
	}
	return ""
}

func (x *Class) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Class) GetSection() string {
	if x != nil {
		return x.Section
	}
	return ""
}

func (x *Class) GetMeetingLocation() string {
	if x != nil {
		return x.MeetingLocation
	}
	return ""
}

func (x *Class) GetMeetingTimes() string {
	if x != nil {
		return x.MeetingTimes
	}
	return ""
}

func (x *Class) GetExam() string {
	if x != nil {
		return x.Exam
	}
	return ""
}

func (x *Class) GetInstructors() []string {
	if x != nil {
		return x.Instructors
	}
	return nil
}

func (x *Class) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *Class) GetSynopsis() string {
	if x != nil {
		return x.Synopsis
	}
	return ""
}

func (x *Class) GetBooks() []string {
	if x != nil {
		return x.Books
	}
	return nil
}

func (x *Class) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_pb_dbRequests_proto protoreflect.FileDescriptor

var file_pb_dbRequests_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x2f, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x73, 0x22, 0x16, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x3e, 0x0a, 0x0f, 0x43, 0x6c, 0x61,
	0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2b, 0x0a, 0x07,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73,
	0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x22, 0xbd, 0x03, 0x0a, 0x05, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x63, 0x68, 0x6f, 0x6f, 0x6c, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x4e, 0x75, 0x6d, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a,
	0x10, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67,
	0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x6d, 0x65, 0x65, 0x74,
	0x69, 0x6e, 0x67, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x6d, 0x65, 0x65, 0x74, 0x69, 0x6e, 0x67, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x12, 0x0a,
	0x04, 0x65, 0x78, 0x61, 0x6d, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x61,
	0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x6f, 0x72, 0x73,
	0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74,
	0x6f, 0x72, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x0d, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x05, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x79, 0x6e,
	0x6f, 0x70, 0x73, 0x69, 0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x79, 0x6e,
	0x6f, 0x70, 0x73, 0x69, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x18, 0x0f,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x62, 0x6f, 0x6f, 0x6b, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x10, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x32, 0x64, 0x0a, 0x0e, 0x44, 0x61, 0x74,
	0x61, 0x62, 0x73, 0x65, 0x57, 0x72, 0x61, 0x70, 0x70, 0x65, 0x72, 0x12, 0x52, 0x0a, 0x0f, 0x52,
	0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x12, 0x20,
	0x2e, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x65, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x1a, 0x1b, 0x2e, 0x64, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x2e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_dbRequests_proto_rawDescOnce sync.Once
	file_pb_dbRequests_proto_rawDescData = file_pb_dbRequests_proto_rawDesc
)

func file_pb_dbRequests_proto_rawDescGZIP() []byte {
	file_pb_dbRequests_proto_rawDescOnce.Do(func() {
		file_pb_dbRequests_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_dbRequests_proto_rawDescData)
	})
	return file_pb_dbRequests_proto_rawDescData
}

var file_pb_dbRequests_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_dbRequests_proto_goTypes = []interface{}{
	(*ReceiveClassesParams)(nil), // 0: dbRequests.ReceiveClassesParams
	(*ClassesResponse)(nil),      // 1: dbRequests.ClassesResponse
	(*Class)(nil),                // 2: dbRequests.Class
}
var file_pb_dbRequests_proto_depIdxs = []int32{
	2, // 0: dbRequests.ClassesResponse.classes:type_name -> dbRequests.Class
	0, // 1: dbRequests.DatabseWrapper.RetrieveClasses:input_type -> dbRequests.ReceiveClassesParams
	1, // 2: dbRequests.DatabseWrapper.RetrieveClasses:output_type -> dbRequests.ClassesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_dbRequests_proto_init() }
func file_pb_dbRequests_proto_init() {
	if File_pb_dbRequests_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_dbRequests_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveClassesParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_dbRequests_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_dbRequests_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Class); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_dbRequests_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_dbRequests_proto_goTypes,
		DependencyIndexes: file_pb_dbRequests_proto_depIdxs,
		MessageInfos:      file_pb_dbRequests_proto_msgTypes,
	}.Build()
	File_pb_dbRequests_proto = out.File
	file_pb_dbRequests_proto_rawDesc = nil
	file_pb_dbRequests_proto_goTypes = nil
	file_pb_dbRequests_proto_depIdxs = nil
}
