// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: prereqInterface.proto

package prereqInterface

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PrereqRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassHistory map[string]int32 `protobuf:"bytes,1,rep,name=ClassHistory,proto3" json:"ClassHistory,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Indices      []string         `protobuf:"bytes,2,rep,name=Indices,proto3" json:"Indices,omitempty"`
	Cases        map[int32]bool   `protobuf:"bytes,3,rep,name=Cases,proto3" json:"Cases,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *PrereqRequest) Reset() {
	*x = PrereqRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prereqInterface_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrereqRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrereqRequest) ProtoMessage() {}

func (x *PrereqRequest) ProtoReflect() protoreflect.Message {
	mi := &file_prereqInterface_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrereqRequest.ProtoReflect.Descriptor instead.
func (*PrereqRequest) Descriptor() ([]byte, []int) {
	return file_prereqInterface_proto_rawDescGZIP(), []int{0}
}

func (x *PrereqRequest) GetClassHistory() map[string]int32 {
	if x != nil {
		return x.ClassHistory
	}
	return nil
}

func (x *PrereqRequest) GetIndices() []string {
	if x != nil {
		return x.Indices
	}
	return nil
}

func (x *PrereqRequest) GetCases() map[int32]bool {
	if x != nil {
		return x.Cases
	}
	return nil
}

type PrereqResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results        map[string]bool `protobuf:"bytes,1,rep,name=Results,proto3" json:"Results,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	InvalidIndices []string        `protobuf:"bytes,2,rep,name=InvalidIndices,proto3" json:"InvalidIndices,omitempty"`
}

func (x *PrereqResponse) Reset() {
	*x = PrereqResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_prereqInterface_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PrereqResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrereqResponse) ProtoMessage() {}

func (x *PrereqResponse) ProtoReflect() protoreflect.Message {
	mi := &file_prereqInterface_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrereqResponse.ProtoReflect.Descriptor instead.
func (*PrereqResponse) Descriptor() ([]byte, []int) {
	return file_prereqInterface_proto_rawDescGZIP(), []int{1}
}

func (x *PrereqResponse) GetResults() map[string]bool {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *PrereqResponse) GetInvalidIndices() []string {
	if x != nil {
		return x.InvalidIndices
	}
	return nil
}

var File_prereqInterface_proto protoreflect.FileDescriptor

var file_prereqInterface_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x65, 0x72, 0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x70, 0x72, 0x65, 0x72, 0x65, 0x71, 0x49,
	0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x22, 0xbb, 0x02, 0x0a, 0x0d, 0x50, 0x72, 0x65,
	0x72, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x54, 0x0a, 0x0c, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x30, 0x2e, 0x70, 0x72, 0x65, 0x72, 0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61,
	0x63, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x72, 0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x2e, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x0c, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x07, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x05, 0x43, 0x61,
	0x73, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x70, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x43, 0x61, 0x73, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x43, 0x61, 0x73, 0x65, 0x73, 0x1a, 0x3f, 0x0a, 0x11, 0x43,
	0x6c, 0x61, 0x73, 0x73, 0x48, 0x69, 0x73, 0x74, 0x6f, 0x72, 0x79, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x1a, 0x38, 0x0a, 0x0a,
	0x43, 0x61, 0x73, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xbc, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x65, 0x72, 0x65,
	0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x72, 0x65,
	0x72, 0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65,
	0x72, 0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x12, 0x26, 0x0a, 0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x49, 0x6e, 0x76, 0x61, 0x6c,
	0x69, 0x64, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x65, 0x73, 0x1a, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0x65, 0x0a, 0x10, 0x50, 0x72, 0x65, 0x72, 0x65, 0x71, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x51, 0x0a, 0x0c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x72, 0x65, 0x72, 0x65, 0x71, 0x73, 0x12, 0x1e, 0x2e, 0x70, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x70, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x50, 0x72, 0x65, 0x72,
	0x65, 0x71, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_prereqInterface_proto_rawDescOnce sync.Once
	file_prereqInterface_proto_rawDescData = file_prereqInterface_proto_rawDesc
)

func file_prereqInterface_proto_rawDescGZIP() []byte {
	file_prereqInterface_proto_rawDescOnce.Do(func() {
		file_prereqInterface_proto_rawDescData = protoimpl.X.CompressGZIP(file_prereqInterface_proto_rawDescData)
	})
	return file_prereqInterface_proto_rawDescData
}

var file_prereqInterface_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_prereqInterface_proto_goTypes = []interface{}{
	(*PrereqRequest)(nil),  // 0: prereqInterface.PrereqRequest
	(*PrereqResponse)(nil), // 1: prereqInterface.PrereqResponse
	nil,                    // 2: prereqInterface.PrereqRequest.ClassHistoryEntry
	nil,                    // 3: prereqInterface.PrereqRequest.CasesEntry
	nil,                    // 4: prereqInterface.PrereqResponse.ResultsEntry
}
var file_prereqInterface_proto_depIdxs = []int32{
	2, // 0: prereqInterface.PrereqRequest.ClassHistory:type_name -> prereqInterface.PrereqRequest.ClassHistoryEntry
	3, // 1: prereqInterface.PrereqRequest.Cases:type_name -> prereqInterface.PrereqRequest.CasesEntry
	4, // 2: prereqInterface.PrereqResponse.Results:type_name -> prereqInterface.PrereqResponse.ResultsEntry
	0, // 3: prereqInterface.PrereqValidation.CheckPrereqs:input_type -> prereqInterface.PrereqRequest
	1, // 4: prereqInterface.PrereqValidation.CheckPrereqs:output_type -> prereqInterface.PrereqResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_prereqInterface_proto_init() }
func file_prereqInterface_proto_init() {
	if File_prereqInterface_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_prereqInterface_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrereqRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_prereqInterface_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PrereqResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_prereqInterface_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_prereqInterface_proto_goTypes,
		DependencyIndexes: file_prereqInterface_proto_depIdxs,
		MessageInfos:      file_prereqInterface_proto_msgTypes,
	}.Build()
	File_prereqInterface_proto = out.File
	file_prereqInterface_proto_rawDesc = nil
	file_prereqInterface_proto_goTypes = nil
	file_prereqInterface_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PrereqValidationClient is the client API for PrereqValidation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PrereqValidationClient interface {
	CheckPrereqs(ctx context.Context, in *PrereqRequest, opts ...grpc.CallOption) (*PrereqResponse, error)
}

type prereqValidationClient struct {
	cc grpc.ClientConnInterface
}

func NewPrereqValidationClient(cc grpc.ClientConnInterface) PrereqValidationClient {
	return &prereqValidationClient{cc}
}

func (c *prereqValidationClient) CheckPrereqs(ctx context.Context, in *PrereqRequest, opts ...grpc.CallOption) (*PrereqResponse, error) {
	out := new(PrereqResponse)
	err := c.cc.Invoke(ctx, "/prereqInterface.PrereqValidation/CheckPrereqs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PrereqValidationServer is the server API for PrereqValidation service.
type PrereqValidationServer interface {
	CheckPrereqs(context.Context, *PrereqRequest) (*PrereqResponse, error)
}

// UnimplementedPrereqValidationServer can be embedded to have forward compatible implementations.
type UnimplementedPrereqValidationServer struct {
}

func (*UnimplementedPrereqValidationServer) CheckPrereqs(context.Context, *PrereqRequest) (*PrereqResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckPrereqs not implemented")
}

func RegisterPrereqValidationServer(s *grpc.Server, srv PrereqValidationServer) {
	s.RegisterService(&_PrereqValidation_serviceDesc, srv)
}

func _PrereqValidation_CheckPrereqs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrereqRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PrereqValidationServer).CheckPrereqs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/prereqInterface.PrereqValidation/CheckPrereqs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PrereqValidationServer).CheckPrereqs(ctx, req.(*PrereqRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PrereqValidation_serviceDesc = grpc.ServiceDesc{
	ServiceName: "prereqInterface.PrereqValidation",
	HandlerType: (*PrereqValidationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckPrereqs",
			Handler:    _PrereqValidation_CheckPrereqs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prereqInterface.proto",
}
